apiVersion: v1
kind: Service
metadata:
  labels:
    app: vehicle-location
    apic-managed: "true"
  creationTimestamp: null
  name: vehicle-location
  namespace: apic-demo
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: http
    name: http
  selector:
    run: vehicle-location
status:
  loadBalancer: {}
---
apiVersion: apps/v1beta
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: vehicle-location
  name: vehicle-location
  namespace: apic-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      run: vehicle-location
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vehicle-location
        run: vehicle-location
    spec:
      containers:
      - image: vbelfoure/acme-vehicle-location-service
        imagePullPolicy: Always
        name: vehicle-location
        ports:
        - containerPort: 8080
          name: http
        resources: {}
status: {}
