apiVersion: v1
kind: Service
metadata:
  labels:
    app: dispatch-service
    apic-managed: "true"
  creationTimestamp: null
  name: dispatch-service
  namespace: apic-demo
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: http
    name: http
  selector:
    run: dispatch-service
status:
  loadBalancer: {}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: dispatch-service
  name: dispatch-service
  namespace: apic-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      run: dispatch-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: dispatch-service
        run: dispatch-service
    spec:
      containers:
      - image: vbelfoure/acme-dispatch-service
        imagePullPolicy: Always
        name: dispatch-service
        ports:
        - containerPort: 8080
          name: http
        resources: {}
status: {}
